### ISSUE TITLE
File / "Open Recent" fails on FAT drives if you disable extended attributes

### ISSUE THREAD

**Issue by Stokestack** [textmate/bugs#35]
I got tired of TextMate claiming that every file on my thumbdrive couldn't be saved, so I disabled all use of extended attributes with:

defaults write com.macromates.TextMate volumeSettings '{ "/" = { extendedAttributes = 0; }; }'

This stopped the complaints, but now any attempt to open a file on this drive through the "recents" menu fails; a document window flashes momentarily on the screen and then disappears. If I double-click on it with Finder or use the File menu, it opens fine.

I tried copying one of the files onto my main drive (APFS), and open-recent functionality works there as expected.

Hm, further detail: If I open the document with TextMate's File menu once and then close it without making changes, open-recent will work. But if I change it and close TextMate (saying Yes to save it), open-recent will fail.

**Comment by sorbits** [comment]
The `volumeSettings` has not been used since 2.0-beta.12.23, which is about four years old, nor should lack of support for extended attributes cause saving to fail, and neither is related to the Open Recent menu.

Please contact [support](https://macromates.com/support) to get help troubleshooting your issue, and they will file an internal bug report, if any actionable information gets uncovered.
